site_name: Local DB Docs
theme: readthedocs
nav:
    - Home: index.md
    - Manual:
        - latest: https://localdb-docs.readthedocs.io/en/devel/
        - 1.4: https://localdb-docs.readthedocs.io/en/devel/
        - 1.3: https://localdb-docs.readthedocs.io/en/1.3/
    - Release Note: release-note.md
    - Contact: contact.md
extra_css:
    - "css/custom.css"
    - "css/theme_extra.css"
    - "css/raliscasts.css"
markdown_extensions:
    - admonition
