site_name: Local DB (Version 1.3) Docs
pages:
    - Top: https://localdb-docs.readthedocs.io/en/top/
    - Home: index.md
    - Pre Requirements and Installation: requirements.md
    - Quick tutorial: tutorial.md
    - Tools: tool.md
    - Scripts: scripts.md
    - Demonstration: demonstration.md
    - Structure: structure.md
    - Advanced: advanced.md
    - Config Samples: config.md
    - FAQ: faq.md
theme: readthedocs
