site_name: Local DB Docs
theme: readthedocs
nav:
    - Home: index.md
    - Manual: manual.md
    - Contact: contact.md
extra_css:
    - "css/custom.css"
    - "css/theme_extra.css"
    - "css/raliscasts.css"
markdown_extensions:
    - admonition
