site_name: Local DB Docs
pages:
    - Home: index.md
    - Pre Requirements and Installation: requirements.md
    - Quick tutorial: tutorial.md
    - Tools: tool.md
    - Demonstration: demonstration.md
    - Structure: structure.md
    - Advanced: advanced.md
    - Config Samples: config.md
    - FAQ: faq.md
theme: readthedocs
