site_name: Local DB Docs
pages:
    - Home: index.md
    - Pre Requirements: requirements.md
    - Quick tutorial: tutorial.md
    - Upload Tool: upload.md
    - Retrieve Tool: retrieve.md
    - Viewer Application: viewer.md
    - Synchronization Tool: sync.md
    - Archive Tool: archive.md
    - ITkPD Interface: itkpd-interface.md
    - scanConsole -W: scanconsole.md
    - DB Accessor: accessor.md
    - Structure: structure.md
    - Advanced: advanced.md
    - Config Samples: config.md
    - FAQ: faq.md
theme: readthedocs
