site_name: Local DB Docs
theme: readthedocs
#theme: rtd-dropdown
nav:
    - Introduction:
        - Home: index.md
        - Installation: installation.md
        - Requirements: requirements-list.md
        - Database Structure: structure.md
        - Relase Note: release-note.md
        - Contact: contact.md
    - Tutorial:
        - Quick tutorial: tutorial.md
        - Demonstrations: demonstration.md
    - Functions:
        - Tools: tool.md
        - Scripts: scripts.md
        - Config samples: config.md
    - FAQ:
        - Advanced: advanced.md
        - dbAccessor related: accessor-faq.md
        - viewer application related: viewer-faq.md
        - others: faq.md
extra_css:
    - "css/custom.css"
markdown_extensions:
    - admonition
