site_name: Local DB Docs
theme: readthedocs
#theme: rtd-dropdown
pages:
    - Home: index.md
    - Database Structure: structure.md
    - Relase Note: release-note.md
    - Contact: contact.md
extra_css:
    - "css/custom.css"
    - "css/theme_extra.css"
    - "css/raliscasts.css"
markdown_extensions:
    - admonition
