site_name: Local DB Docs
pages:
    - Home: index.md
    - Pre Requirements: requirements.md
    - Installation: install.md
    - Quick tutorial: tutorial.md
    - Upload Tool: upload.md
    - Retrieve Tool: retrieve.md
    - Viewer Application: viewer.md
    - Synchronization Tool: sync.md
    - Archive Tool: archive.md
    - Structure: structure.md
    - LocalDB: localdb.md
    - Advanced: advanced.md
    - Config Samples: config.md
    - FAQ: faq.md
theme: readthedocs
